# Generated by Django 4.2.2 on 2023-06-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='claas_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
