# Generated by Django 4.2.2 on 2023-06-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_room_claas_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='claas_name',
        ),
    ]
