# Generated by Django 3.2.11 on 2022-01-26 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220126_1920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['updated', '-created']},
        ),
    ]
