# Generated by Django 4.2.2 on 2023-06-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_room_claas_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='participants',
        ),
    ]
